### ISSUE TITLE
Debate: documentation

### ISSUE THREAD

**Issue by vladmunteanu** [vladmunteanu/starlette-jsonapi#15]
We should switch to a dedicated documentation platform as opposed to keeping things in README.
I think [readthedocs](https://readthedocs.io) would be a good fit, but there are others that could work too, waiting for some ideas before putting more time into this.

This could be a central place for discussing things related to documentation.

**Comment by khornberg** [comment]
What are the purposes or intents of the docs?

Is it to show examples? explain how to use? show the python api of starlette-jsonapi?

starlette itself uses mkdocs (and the material theme)

are you thinking you want something stock like that or something more custom?

**Comment by vladmunteanu** [comment]
@khornberg Thanks for replying so quickly! I honestly don't have experience with setting up proper documentation, so I'm open to suggestions. I've replied below, and we can set the main comment based on this discussion when we make a decision.

Purpose:
- To present a minimal getting started guide for installation, setting up within a Starlette app and some reading material maybe.
- To explain how to use and show examples
- To present the python API reference of starlette-jsonapi

Theme: 
- I think a stock theme will do fine, I personally prefer the one that [marshmallow-jsonapi](https://marshmallow-jsonapi.readthedocs.io/en/latest/) uses. I consider it easier to read and structure.

**Comment by pOctav** [comment]
I think these are all good ides. The README should only have a simple overview and installation instructions, whereas the documentation should have a more detailed description of the framework's components.
I also agree with readthedocs as the documentation solution, I think it's a good platform
