### ISSUE TITLE
Debate: OpenAPI integration

### ISSUE THREAD

**Issue by vladmunteanu** [vladmunteanu/starlette-jsonapi#22]
This is a nice to have I imagine, since it would "standardize" the way APIs are documented.

I've done very little research on this subject, so any input is greatly appreciated.

A good starting point might be to look at integrating https://github.com/marshmallow-code/apispec.

**Comment by khornberg** [comment]
I've had that idea as well

**Comment by khornberg** [comment]
From what I've found the first question is what is the intent of the docs
Do we want to provide a general JSON:API spec _without_ specifics?
Do we want to provide a specific spec?

[This is a generic spec](https://gist.github.com/khornberg/acaa6e1c9041fc8762764fb3b4b8efd8) that could be used to document the structure and urls but would not give specific data

If we want to provide specific data a few questions arise

* How do we know what relationships to show? They are not all required. Do we show what is possible?
* How do we keep the `id` attribute out of the attributes field?
	I made a subclass
```
from starlette_apispec import APISpecSchemaGenerator

class JSONAPISpec(APISpecSchemaGenerator):

    def get_schema(self, routes: typing.List[BaseRoute]) -> dict:
		...
        self.spec.components.schema(schema.__name__, schema=schema)
        # `id` is part of the schema for serialization but not an attribute where this is used
        # This removes the `id` after the fact for lack of a way to exclude in the marshmallow plugin
        self.spec.components._schemas.get(schema.__name__)["properties"].pop("id")
```

* How do we indicate what errors a handler actually returns?
* How do we indicate that a handler returns a 200, 202, or 204?

**Comment by vladmunteanu** [comment]
@khornberg Wow, thanks for looking into this, that's really more than I know at the moment :D . I opened the starlette_apispec project at one point but didn't do much with it.

I haven't played with apispec so I don't know what happens if you feed it a JSONAPISchema yet. If the ˋidˋ field is included as an attribute, I would expect other fields defined in marshmallow_jsonapi to be problematic, like meta and relationship.

Some of my early thoughts, but I'll research the subject over the weekend and next week:
- I'm not a huge fan of documentation in docstrings (I know, it kinda goes against apispec), I would prefer a more "programmable" way of doing docs. Now this might be dumb: I was toying with the idea of building documentation through some means that are similar to pytest fixture building.
- We should probably aim at providing a generic spec, with data, and do a best effort at guessing what attributes are required based on some marshmallow attributes and the json:API spec recommendations.

**Comment by vladmunteanu** [comment]
Still a bunch of things I wish I could discuss, but I'm still learning about this.
However, I think I'm a bit closer to what I was suggesting previously, so an OpenAPI integration in starlette-jsonapi would touch on these:
- support generating an OpenAPI 3 schema via decorators, instead of parsing docstrings
- be somewhat similar to the implementation in https://github.com/python-restx/flask-restx
- a designated class would be instantiated and used to generate the schema
	- it should have methods implemented as decorators:
```
openapi = OpenAPI()
# later, in some resource implementation:			

@openapi.document()
class UsersResource(BaseResource):
	
	@openapi.response(status_code=200, example=<a callable or a dict object>)
	@openapi.parameter(in_='query', name='custom_param', type_=int, required=True, description='Some custom parameter')
	@openapi.helpers.filter_parameter(name='email', description='Support to filter users via ?filter[email]= requests')  # not sure if we should scope this under `helpers`
	async def get(........):
		.....

```

- examples should be passed as variables or callables that should return the variable (similar to fixtures in pytest)
- secondary goal is to have documentation testable through something like pytest, if needed

**Comment by vladmunteanu** [comment]
Added in 2.1.0
