### ISSUE TITLE
Exceptions schema is missing from the schemas object

### ISSUE THREAD

**Issue by itakouna** [vladmunteanu/starlette-jsonapi#38]
As pointed out in the example, I'm using the "404" error as the following

```
from starlette_jsonapi.exceptions import ResourceNotFound
class PostNotFound(ResourceNotFound):
    detail = 'Post not found.'

......

@with_openapi_info(responses={'200': schema, '404': exceptions.PostNotFound})
async def get(self, id=None, *args, **kwargs) -> Response:
```
Then I got the following error when verifying the generated open API JSON file
```
Resolver error at paths./api/post/{id}.get.responses.404.content.application/vnd.api+json.schema.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/PostNotFound-404 does not exist in document
```

Is this a bug? or Did I miss something?

**Comment by vladmunteanu** [comment]
Hello @itakouna!

I assume you are referring to [sample-plain](https://github.com/vladmunteanu/starlette-jsonapi/tree/master/examples/sample-plain)
I tried running the example again, this time with python 3.7 and it works, so I assume it must be something related to how schema generation is configured. Make sure you use the correct classes from `starlette_jsonapi.openapi`:

```
    schemas = JSONAPISchemaGenerator(
        APISpec(
            title='Accounts Management API',
            version='1.0',
            openapi_version='3.0.3',
            info={'description': 'An example API for managing accounts.'},
            plugins=[JSONAPIMarshmallowPlugin()],
        )
    )
```

**Comment by vladmunteanu** [comment]
Try running that example first if you haven't already, some helper steps:

- setting up environment:
```pyenv global 3.7.13 && pyenv virtualenv -p python3.7 sj-ex-plain```
- activating environment:
```pyenv activate sj-ex-plain```
- installing dependencies for 3.7 (example was 3.6 at the time):
```pip install pip-tools && pip-compile --output-file=requirements.txt requirements.in && pip-sync requirements.txt```
- running the service:
```python start_service.py```
- get the openapi schema json from http://127.0.0.1:8000/schema
- feed it to a swagger UI (replace <PATH_TO_SCHEMA> with the path where you saved the above schema):
```docker run -p 80:8080 -e SWAGGER_JSON=/sj/schema.json -v <PATH_TO_SCHEMA>:/sj swaggerapi/swagger-ui```

**Comment by itakouna** [comment]
Great! Thanks. I've recreated the `pyenv` and worked well. I've also tested with python `3.10.0` and work like a charm.
